import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import StoreProvider from './StoreProvider';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={montserrat.className}>
          <div id="portal" />
          <div className="bg-gradient-to-r from-indigo-500 via-purple-500 bg-purple-400 min-h-full px-5">
            <div className="max-w-screen-xl m-auto min-h-full">{children}</div>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
